import {escapeHTML as h,resolvedEvents,bounds,findCurrent,findNext,countdown,routeURL,safeTricount} from './core.js';
import {setupVenues} from './venue-cards.js';
const $=s=>document.querySelector(s),KEY='ry-2026:v1:';
function read(key,fallback){try{const val=localStorage.getItem(KEY+key);return val===null?fallback:JSON.parse(val);}catch{return fallback;}}
function save(key,val){try{localStorage.setItem(KEY+key,JSON.stringify(val));}catch{$('#offline-status').textContent='Настройки не сохраняются в этом браузере';}}
const moscowDate=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Moscow',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
let selected=moscowDate()>='2026-09-14'?1:0,trip;
function passengersHTML(e){return e.passengers?.length?`<div class="passengers" aria-label="Пассажиры и места">${e.passengers.map(p=>`<div><strong>${h(p.name)}</strong><span>Вагон <b>${h(p.car)}</b> · место <b>${h(p.seat)}</b></span></div>`).join('')}</div>`:'';}
const allEvents=()=>trip.days.flatMap(d=>resolvedEvents(d));
function eventHTML(e,print=false){const {start,end}=bounds(e),now=Date.now();return `<article class="event ${e.kind} ${start<=now&&now<end?'current':''} ${end<now?'is-past':''}" id="${print?'print-':''}${e.id}"><div class="event-time">${e.start}<small>до ${e.end}${e.end<e.start?' · 15.09':''}</small></div><div class="event-body"><div class="event-meta"><span class="badge">${h(e.status)}</span><span>${h(e.meta)}</span></div><h3>${h(e.title)}</h3><p>${h(e.description)}</p>${passengersHTML(e)}<div class="place-buttons">${e.places.map(id=>`<button data-place="${id}" aria-label="Карточка: ${h(trip.places[id].name)}">${h(trip.places[id].name)} ↗</button>`).join('')}</div>${e.route?`<a class="route-link" href="${h(routeURL(e.route,trip.places))}" target="_blank" rel="noopener noreferrer">${e.route.mode==='auto'?'Маршрут на такси':'Пешеходный маршрут'} в Яндекс Картах ↗</a>`:''}<div class="print-addresses">${e.places.map(id=>`${h(trip.places[id].name)}: ${h(trip.places[id].address)}`).join('<br>')}</div></div></article>`;}
function renderDay(){document.querySelectorAll('[data-day]').forEach(b=>{const active=+b.dataset.day===selected;b.setAttribute('aria-selected',active);b.tabIndex=active?0:-1;});$('#day-panel').setAttribute('aria-labelledby',`tab-${selected?14:13}`);$('#day-caption').textContent=trip.days[selected].subtitle;$('#timeline').innerHTML=resolvedEvents(trip.days[selected]).map(e=>eventHTML(e)).join('');tick();}
function tick(){if(!trip)return;const now=Date.now(),events=allEvents(),current=findCurrent(events,now),next=findNext(events,now),e=current||next;$('#now-label').textContent=current?'СЕЙЧАС ПО ПЛАНУ':next?'СЛЕДУЮЩИЙ ПУНКТ':'ПОЕЗДКА ЗАВЕРШЕНА';$('#now-title').textContent=e?e.title:'Мы в Москве';$('#now-copy').textContent=current?`До конца блока ${countdown(bounds(current).end-now)}. Далее: ${next?.title||'прибытие в Москву'}.`:next?`Начало ${next.date.slice(8)} сентября в ${next.start} · через ${countdown(bounds(next).start-now)}.`:'Прибытие 15 сентября в 00:32. Маршрут остаётся доступен.';$('#now-action').innerHTML=e?`<button class="text-button" data-jump="${e.id}">Открыть пункт маршрута ↓</button>`:'';
 const train=events.find(x=>x.kind==='train'&&bounds(x).end>now);$('#train-title').textContent=train?`${train.start} · ${train.date.slice(8)} сентября`:'Все переезды завершены';$('#train-copy').textContent=train?`${train.title}${bounds(train).start<=now?' · в пути':` · через ${countdown(bounds(train).start-now)}`}`:'Москва · 15 сентября, 00:32';
 document.querySelectorAll('#timeline .event').forEach(el=>{const event=events.find(x=>x.id===el.id);if(!event)return;el.classList.toggle('current',bounds(event).start<=now&&now<bounds(event).end);el.classList.toggle('is-past',bounds(event).end<now);});}
function jump(id){const idx=trip.days.findIndex(d=>id.startsWith(d.date));selected=Math.max(0,idx);renderDay();requestAnimationFrame(()=>{document.getElementById(id)?.scrollIntoView({block:'start'});});}
function checks(){const names=['Билеты на все три переезда','Документы','Зарядки и power bank','Рюкзак и вещи на одну ночь','Карта или билет для МЦД','Подтвердить экскурсию в музее на 13:00','Забронировать рестораны при необходимости'];const stored=read('checklist',[]),done=Array.isArray(stored)?stored:[];$('#checklist').innerHTML=names.map((n,i)=>`<label class="check-item"><input type="checkbox" data-check="${i}" ${done.includes(i)?'checked':''}><span>${n}</span></label>`).join('');const update=()=>{const ids=[...document.querySelectorAll('[data-check]:checked')].map(x=>+x.dataset.check);save('checklist',ids);$('#check-count').textContent=`${ids.length} / 7`;};$('#check-count').textContent=`${done.filter(i=>Number.isInteger(i)&&i>=0&&i<7).length} / 7`;$('#checklist').addEventListener('change',update);
 const booked=read('bookings',{});$('#bookings').innerHTML=[['supberry','SupBerry · 13.09, 11:30'],['lucia','Osteria Lucia · 14.09, 18:30'],['soviet','«Советская эпоха» · 13.09, 13:00']].map(([id,name])=>`<div class="booking-item"><label class="check-item"><input type="checkbox" data-booking="${id}" ${booked?.[id]===true?'checked':''}><span>${name}<br><small>${booked?.[id]===true?'Вы отметили подтверждение':'Не подтверждено'}</small></span></label><button data-place="${id}" aria-label="Контакты ${h(name)}">Контакты</button></div>`).join('');$('#bookings').addEventListener('change',e=>{if(!e.target.matches('[data-booking]'))return;const state={};document.querySelectorAll('[data-booking]').forEach(i=>state[i.dataset.booking]=i.checked);save('bookings',state);e.target.parentElement.querySelector('small').textContent=e.target.checked?'Вы отметили подтверждение':'Не подтверждено';});}
function transport(){$('#transport-body').innerHTML=allEvents().filter(e=>e.kind==='train').map((e,i)=>`<div class="rail-segment"><h3>${e.date.slice(8)} сентября · ${e.start} → ${e.end}${e.end<e.start?' (+1 день)':''}</h3><p><b>${h(e.title)}</b></p><p>${h(e.description)}</p>${passengersHTML(e)}<div class="actions">${e.places.map(id=>`<button data-place="${id}">${h(trip.places[id].name)}</button>`).join('')}<a href="${h(e.scheduleUrl)}" target="_blank" rel="noopener noreferrer">Расписание на дату ↗</a></div></div>`).join('')+`<details><summary>Если пропустили электричку</summary><div class="details-body"><p>Автобусы в сторону Ярославля ориентировочно в 07:30, 07:40 и далее. Это резерв, точное время и наличие мест уточнить в кассе / Расписаниях. Утреннюю прогулку в Ярославле придётся сократить.</p><button data-place="bus">Рыбинский автовокзал ↗</button></div></details>`;$('#home-map').href=trip.places.home.map;$('#home-route').href=routeURL({stops:['home','rybstation'],mode:'auto'},trip.places);}
function finance(){const saved=safeTricount(read('finance',trip.financeUrl));function show(url){$('#finance-link').hidden=!url;if(url)$('#finance-link').href=url;}$('#finance-url').value=saved||'';show(saved);$('#finance-form').addEventListener('submit',e=>{e.preventDefault();const value=$('#finance-url').value.trim(),url=safeTricount(value);if(value&&!url){$('#finance-status').textContent='Нужна HTTPS-ссылка с сайта tricount.com.';return;}save('finance',url||'');show(url);$('#finance-status').textContent=value?'Ссылка сохранена на этом устройстве.':'Ссылка удалена.';});}
async function weather(){try{const res=await fetch('./data/weather.json');if(!res.ok)throw Error('weather');const data=await res.json();const temp=n=>`${n>0?'+':''}${Math.round(n)}°`;$('#weather-body').innerHTML=data.days.map(d=>`<div class="weather-row"><span>${h(d.city)}<small>${d.date.slice(8)} сентября</small></span><strong>${temp(d.min)}…${temp(d.max)}</strong></div>`).join('')+`<p class="weather-source"><a href="https://open-meteo.com/" target="_blank" rel="noopener noreferrer">Open-Meteo</a><br>Обновлено ${new Intl.DateTimeFormat('ru',{timeZone:'Europe/Moscow',day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'}).format(new Date(data.generatedAt))} МСК${Date.now()-Date.parse(data.generatedAt)>36*3600000?' · сохранённый прогноз, может устареть':''}</p>`;}catch{$('#weather-body').innerHTML='<p>Прогноз сейчас недоступен. Расписание доступно.</p>';}}
let printing=false,originalDetails=[];function preparePrint(){if(printing||!trip)return;printing=true;originalDetails=[...document.querySelectorAll('#essentials details')].map(el=>[el,el.open]);originalDetails.forEach(([el])=>el.open=true);$('#day-panel').hidden=true;const box=document.createElement('div');box.id='print-itinerary';box.innerHTML=trip.days.map((d,i)=>`<section class="print-day"><h2>${d.label}</h2><p>Московское время</p>${resolvedEvents(d).map(e=>eventHTML(e,true)).join('')}</section>`).join('');$('.schedule').append(box);}function finishPrint(){if(!printing)return;$('#print-itinerary')?.remove();$('#day-panel').hidden=false;originalDetails.forEach(([el,open])=>el.open=open);printing=false;}
window.addEventListener('beforeprint',preparePrint);window.addEventListener('afterprint',finishPrint);for(const id of ['#print','#print-bottom'])$(id).addEventListener('click',()=>window.print());
async function offline(){const el=$('#offline-status');if(!('serviceWorker'in navigator)){el.textContent='Офлайн не поддерживается этим браузером';return;}try{await navigator.serviceWorker.register('./sw.js');await navigator.serviceWorker.ready;el.textContent=navigator.onLine?'Готово для офлайн':'Офлайн · сохранённое расписание';const update=()=>el.textContent=navigator.onLine?'Готово для офлайн':'Офлайн · сохранённое расписание';window.addEventListener('online',update);window.addEventListener('offline',update);}catch{el.textContent='Офлайн-копия ещё не готова; обновите при связи';}}
try{const res=await fetch('./data/trip.json');if(!res.ok)throw Error('trip');trip=await res.json();setupVenues(trip.places);renderDay();transport();checks();finance();document.querySelectorAll('[data-day]').forEach(b=>b.addEventListener('click',()=>{selected=+b.dataset.day;renderDay();}));document.querySelector('[role=tablist]').addEventListener('keydown',e=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;e.preventDefault();selected=e.key==='Home'?0:e.key==='End'?1:1-selected;renderDay();document.querySelector(`[data-day="${selected}"]`).focus();});document.addEventListener('click',e=>{const b=e.target.closest('[data-jump]');if(b)jump(b.dataset.jump);});$('#jump-now').addEventListener('click',()=>{const e=findCurrent(allEvents())||findNext(allEvents());if(e)jump(e.id);else{$('#day-caption').scrollIntoView();}});setInterval(tick,30000);weather();offline();}catch(err){$('#timeline').innerHTML='<p>Не удалось загрузить расписание. Обновите страницу при связи или <a href="route.md">откройте текстовый маршрут</a>.</p>';$('#now-title').textContent='Расписание не загружено';$('#now-copy').textContent='Попробуйте обновить страницу.';$('#offline-status').textContent='Нужна загрузка при связи';console.error('Trip loading failed',err);}
