import {escapeHTML as h,destinationURL,routeURL} from './core.js';
export function setupVenues(places){const dialog=document.querySelector('#venue-dialog');let opener;const close=()=>{dialog.close();document.body.style.overflow='';opener?.focus();};
 document.querySelector('#venue-close').addEventListener('click',close);
 dialog.addEventListener('cancel',e=>{e.preventDefault();close();});
 dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)close();}});
 document.addEventListener('click',e=>{const b=e.target.closest('[data-place]');if(!b)return;const p=places[b.dataset.place];if(!p)return;opener=b;
 const onward=p.id==='home'?{stops:['home','rybstation'],mode:'auto'}:p.id==='pech'?{stops:['pech','yarstation'],mode:'auto'}:p.id==='roscha'?{stops:['roscha','home'],mode:'auto'}:null;
 document.querySelector('#venue-body').innerHTML=`<span class="badge">${h(p.status)}</span><h2 id="venue-title">${h(p.name)}</h2><div class="venue-subtitle">${h(p.city)} · ${h(p.kind)} · ${h(p.duration)}</div><p class="venue-description">${h(p.description)}</p><dl class="venue-facts"><dt>Адрес</dt><dd>${h(p.address)}</dd><dt>Режим</dt><dd>${h(p.hours)}</dd>${p.phone?`<dt>Телефон</dt><dd><a href="tel:${p.phone.replace(/[^+\d]/g,'')}">${h(p.phone)}</a></dd>`:''}${p.booking?`<dt>Бронь</dt><dd>${h(p.booking)}</dd>`:''}</dl><p class="venue-rain"><b>Если дождь.</b> ${h(p.rain)}</p><div class="actions"><a href="${h(p.map)}" target="_blank" rel="noopener noreferrer">Яндекс Карты ↗</a><a href="${h(destinationURL(p))}" target="_blank" rel="noopener noreferrer">Маршрут сюда ↗</a>${onward?`<a href="${h(routeURL(onward,places))}" target="_blank" rel="noopener noreferrer">${p.id==='roscha'?'Такси к жилью':'Такси на вокзал'} ↗</a>`:''}</div><div class="venue-source">Сведения проверены ${p.checked}. ${p.source?`<a href="${h(p.source)}" target="_blank" rel="noopener noreferrer">Источник ↗</a>`:'Источник: карточка Яндекс Карт.'}</div>`;
 dialog.showModal();dialog.scrollTop=0;document.body.style.overflow='hidden';document.querySelector('#venue-close').focus();});
}
