import {readFile,writeFile,rename} from 'node:fs/promises';
import {pathToFileURL} from 'node:url';
export const TARGETS=[{city:'Рыбинск',date:'2026-09-13',latitude:58.05,longitude:38.85,index:0},{city:'Ярославль',date:'2026-09-14',latitude:57.63,longitude:39.88,index:1}];
export function normalize(raw,generatedAt=new Date().toISOString()){
 if(!Array.isArray(raw)||raw.length!==2)throw Error('Expected two cities');
 return {source:'Open-Meteo',sourceURL:'https://open-meteo.com/',license:'CC BY 4.0',timezone:'Europe/Moscow',generatedAt,days:TARGETS.map(t=>{const entry=raw[t.index],d=entry.daily,i=d?.time?.indexOf(t.date);if(i===undefined||i<0||entry.utc_offset_seconds!==10800||Math.abs(entry.latitude-t.latitude)>.15||Math.abs(entry.longitude-t.longitude)>.15)throw Error('Invalid city/date/timezone');const min=d.temperature_2m_min[i],max=d.temperature_2m_max[i],rainProbability=d.precipitation_probability_max[i],code=d.weather_code[i];if(![min,max,rainProbability,code].every(Number.isFinite)||min>max||rainProbability<0||rainProbability>100)throw Error('Invalid forecast values');return {city:t.city,date:t.date,latitude:t.latitude,longitude:t.longitude,min,max,rainProbability,code,summary:code<=1?'Ясно / малооблачно':code<=3?'Облачно':code<50?'Туман':code<70?'Возможен дождь':code<80?'Возможен снег':'Возможны осадки',sunrise:d.sunrise[i],sunset:d.sunset[i]};})};
}
export async function updateWeather({fetcher=fetch,now=new Date(),file=new URL('../data/weather.json',import.meta.url)}={}){const date=new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Moscow',year:'numeric',month:'2-digit',day:'2-digit'}).format(now);if(date>'2026-09-14'||date<'2026-08-30'){console.log('Trip outside forecast horizon; keeping saved forecast.');return false;}
 try{const url=new URL('https://api.open-meteo.com/v1/forecast');url.search=new URLSearchParams({latitude:'58.05,57.63',longitude:'38.85,39.88',daily:'temperature_2m_max,temperature_2m_min,precipitation_probability_max,weather_code,sunrise,sunset',timezone:'Europe/Moscow',start_date:'2026-09-13',end_date:'2026-09-14'});const response=await fetcher(url,{signal:AbortSignal.timeout(20000)});if(!response.ok)throw Error(`Weather HTTP ${response.status}`);const normalized=normalize(await response.json(),now.toISOString());const tmp=new URL(file.href+'.tmp');await writeFile(tmp,JSON.stringify(normalized,null,2)+'\n');await rename(tmp,file);console.log('Saved validated forecast for two city/day pairs.');return true;}catch(error){await readFile(file);console.warn(`Forecast not updated; keeping saved data: ${error.message}`);return false;}}
if(process.argv[1]&&import.meta.url===pathToFileURL(process.argv[1]).href)await updateWeather();
